name: Deploy to VPS

on:
  push:
    branches:
      - main  # Change this if your main branch has a different name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 82.29.169.7
          username: root
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            cd /root/zebackend  # Go to your backend folder
            git pull origin main  # Pull the latest code
            npm install  # Install dependencies
            pm2 restart all  # Restart your backend
